$fn=50;
weight=40;
height=5;
diameter=4;
text1="STICLab";
union(){
   difference(){
    cube([weight,weight/6,height],center=true);
    translate([0,3,0])cylinder(d=diameter,h=height*10,center=true);
    translate([0,-3,0])cylinder(d=diameter,h=height*10,center=true);
   }
   translate([2,-1.5,2.4])linear_extrude(height=0.2,twist=2)text(text1,size=4,font="impact:style=regular",spacing=1,direction="ltr");
}